[build-system]
requires = ["setuptools>=80", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "get-lsst-refcats"
license = {file = "LICENSE"}
readme = "README.md"
authors = [
    { name = "Steven Stetzler", email = "steven.stetzler@gmail.com" }
]
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: MIT License",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
]
dynamic = ["version"]
requires-python = ">=3.9"
dependencies = [
    "astropy",
    "requests",
    "joblib",
]
description = "Get reference catalogs for the LSST Science Pipelines."

[project.urls]
"Source Code" = "https://github.com/stevenstetzler/get-lsst-refcats"

[project.scripts]
lsst-refcats = "get_lsst_refcats.trim:main"

[tool.setuptools_scm]
write_to = "src/get_lsst_refcats/_version.py"
version_scheme = "guess-next-dev"
local_scheme = "no-local-version"

[project.optional-dependencies]
dev = [
    "pytest"
]

